Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,11 +26,11 @@ jobs:
         run: ./gradlew build
       - name: Run Unit Tests
         run: ./gradlew common:testDebug
-      - name: Publish Test Results
-        uses: mikepenz/action-junit-report@v5
-        if: success() || failure()
-        with:
-          report_paths: '**/common/build/test-results/testDebugUnitTest/TEST-*.xml'
+      # - name: Publish Test Results
+      #   uses: mikepenz/action-junit-report@v5
+      #   if: success() || failure()
+      #   with:
+      #     report_paths: '**/common/build/test-results/testDebugUnitTest/TEST-*.xml'
 
   run_ui_tests:
     name: Build and UI Test
